Removed computation steps no longer needed for CauseMos API 3.0.0
ml4ai/delphi pull request #506
Opened 2021-11-16 22:41 UTC by jastier

2021-11-18 04:09 UTC, adarshp requested changes
@jastier - you might as well remove lines 91-96 of `delphi_rest_api.cpp` as well, since you've removed the code corresponding to that comment...

2021-11-18 06:50 UTC, jastier commented
Done.

On Wed, Nov 17, 2021 at 9:09 PM Adarsh Pyarelal ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> @jastier <https://github.com/jastier> - you might as well remove lines
> 91-96 of delphi_rest_api.cpp as well, since you've removed the code
> corresponding to that comment...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ml4ai/delphi/pull/506#pullrequestreview-809451088>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACD6H4YUNMEW6NR24BEGWSLUMR363ANCNFSM5IFO7WRA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-19 18:06 UTC, manujinda commented on apps/delphi_rest_api.cpp
>              unordered_map<string, vector<string>> res_data;
Do we need this variable and the 2 lines that follow?

I could not locate a usage of it.

2021-11-19 18:40 UTC, adarshp approved these changes

2021-11-23 14:48 UTC, merged